# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_ITH_opt <- function(RD, log_DP, LBC, BB, uniq_BB, uniq_CN_MA, eS, purity, tCN, pi_eps0, pi0, unc_qq0, mstep = TRUE, max_iter = 4e3L, eps = 1e-6, show = TRUE) {
    .Call('_SMASH_Rcpp_ITH_opt', PACKAGE = 'SMASH', RD, log_DP, LBC, BB, uniq_BB, uniq_CN_MA, eS, purity, tCN, pi_eps0, pi0, unc_qq0, mstep, max_iter, eps, show)
}

