# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_norm <- function(a) {
    .Call('_SMASH_Rcpp_norm', PACKAGE = 'SMASH', a)
}

Rcpp_logSumExp <- function(log_x) {
    .Call('_SMASH_Rcpp_logSumExp', PACKAGE = 'SMASH', log_x)
}

Rcpp_min_diff <- function(x) {
    .Call('_SMASH_Rcpp_min_diff', PACKAGE = 'SMASH', x)
}

Rcpp_log_binom_coef <- function(n, x) {
    .Call('_SMASH_Rcpp_log_binom_coef', PACKAGE = 'SMASH', n, x)
}

Rcpp_vartheta_to_eta <- function(x) {
    .Call('_SMASH_Rcpp_vartheta_to_eta', PACKAGE = 'SMASH', x)
}

Rcpp_vartheta_to_qq <- function(xx) {
    .Call('_SMASH_Rcpp_vartheta_to_qq', PACKAGE = 'SMASH', xx)
}

Rcpp_ITH_obsLL_Z <- function(RD, ZZ, uniq_CN_MA, BB, pi, eS, purity, qq) {
    .Call('_SMASH_Rcpp_ITH_obsLL_Z', PACKAGE = 'SMASH', RD, ZZ, uniq_CN_MA, BB, pi, eS, purity, qq)
}

Rcpp_ITH_compLL <- function(RD, ZZ, uniq_CN_MA, pi, eS, purity, qq) {
    .Call('_SMASH_Rcpp_ITH_compLL', PACKAGE = 'SMASH', RD, ZZ, uniq_CN_MA, pi, eS, purity, qq)
}

Rcpp_ITH_compGRAD <- function(RD, ZZ, uniq_CN_MA, eS, purity, qq, tCN) {
    .Call('_SMASH_Rcpp_ITH_compGRAD', PACKAGE = 'SMASH', RD, ZZ, uniq_CN_MA, eS, purity, qq, tCN)
}

Rcpp_ITH_Mstep_BFGS <- function(RD, ZZ, uniq_CN_MA, pi, eS, purity, tCN, params0, qq, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    invisible(.Call('_SMASH_Rcpp_ITH_Mstep_BFGS', PACKAGE = 'SMASH', RD, ZZ, uniq_CN_MA, pi, eS, purity, tCN, params0, qq, max_iter, eps, show))
}

Rcpp_ITH_opt <- function(RD, BB, uniq_BB, uniq_CN_MA, eS, purity, tCN, pi0, unc_qq0, mstep = TRUE, max_iter = 4e3L, eps = 1e-6, show = TRUE) {
    .Call('_SMASH_Rcpp_ITH_opt', PACKAGE = 'SMASH', RD, BB, uniq_BB, uniq_CN_MA, eS, purity, tCN, pi0, unc_qq0, mstep, max_iter, eps, show)
}

